name: SQLDialectTest

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Test SQL Dialect
    runs-on: ubuntu-20.04
    steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Checkout project
      uses: actions/checkout@v2
      with:
        path: sandbox

    - name: Install Python depends
      run: |
        python -m pip install -r ${GITHUB_WORKSPACE}/sandbox/experimental/sql/requirements.txt

    - name: Check format with yapf
      run: |
        # Returns en error code if the files are not formatted
        yapf --diff -r ${GITHUB_WORKSPACE}/sandbox/experimental/sql

    - name: Test
      run: |
        cd ${GITHUB_WORKSPACE}/sandbox
        lit -v ${GITHUB_WORKSPACE}/sandbox/experimental/sql/test
